# Generated by Django 4.2 on 2024-03-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=150)),
                ("price", models.IntegerField()),
                ("discount", models.CharField(max_length=10)),
                ("tag", models.CharField(max_length=20)),
                ("genre", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="tag",
            name="genre",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
