# Generated by Django 4.2 on 2024-03-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_remove_tag_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="create_at",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
