# Generated by Django 4.2 on 2024-03-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_rename_tag_searchdata_rename_tag_searchdata_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchdata",
            old_name="products",
            new_name="genre",
        ),
        migrations.AddField(
            model_name="searchdata",
            name="tag",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
