# Generated by Django 4.2 on 2024-03-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "관리자"),
                    ("seller", "판매자"),
                    ("vip", "vip"),
                    ("customer", "소비자"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
